# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-03 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuExam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
